name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: ["ItsMateo20/Cloud"]
assignees:
  - ItsMateo20
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide the following details to help us identify and address the issue.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com, discord username
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and provide steps to reproduce it.
      placeholder: Describe the bug in detail.
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: Enter the browser you are using
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy and paste any relevant log output to assist with debugging.
      render: shell
