name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ItsMateo20
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and provide steps to reproduce it.
      placeholder: Describe the bug in detail.
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: Enter the browser you are using
    validations:
      required: true
  - type: checkboxes
    id: tried-solutions
    attributes:
      label: Tried Solutions
      description: Check the solutions you have tried before reporting the bug.
      options:
        - label: "I'm on the most recent release of Cloud Storage"
          required: true
        - label: I have tried reinstalling Cloud Storage.
          required: true
        - label: I have read the README and FAQ sections for a solution.
          required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy and paste your hole log output to assist with debugging.
      render: shell
    validations:
      required: true
